import { RegisterKeys } from '../types';

export const FormFieldsData = {
  name: {
    name: 'name',
    type: 'text',
    id: 'name',
    label: 'Name',
    placeholder: 'Enter the name',
    inputKey: RegisterKeys.name,
  },
  age: {
    name: 'age',
    type: 'number',
    id: 'age',
    label: 'Age',
    placeholder: 'Enter the age',
    inputKey: RegisterKeys.age,
  },
  email: {
    name: 'email',
    type: 'text',
    id: 'email',
    label: 'Email',
    placeholder: 'Enter the email',
    inputKey: RegisterKeys.email,
  },
  password: {
    name: 'password',
    type: 'password',
    id: 'password',
    label: 'Password',
    placeholder: 'Create a password',
    inputKey: RegisterKeys.password,
  },
  passwordRepeat: {
    name: 'passwordRepeat',
    type: 'password',
    id: 'passwordRepeat',
    label: 'Confirm Password',
    placeholder: 'Enter your password again',
    inputKey: RegisterKeys.passwordRepeat,
  },
  img: {
    name: 'img',
    type: 'file',
    id: 'img',
    label: 'Upload image',
    placeholder: '',
    inputKey: RegisterKeys.img,
  },
  t_c: {
    name: 't_c',
    type: 'checkbox',
    id: 't_c',
    label: 'Accept T&C',
    placeholder: '',
    inputKey: RegisterKeys.t_c,
  },
  gender: {
    name: 'gender',
    type: 'select',
    id: 'gender',
    label: 'Gender',
    placeholder: 'Select the gender',
    inputKey: RegisterKeys.gender,
  },
  countries: {
    name: 'country',
    type: 'select',
    id: 'country',
    label: 'Country',
    placeholder: 'Select the country',
    inputKey: RegisterKeys.country,
  },
};
