export const UncontrolledInputs = {
  name: {
    name: 'name',
    type: 'text',
    id: 'name',
    label: 'Name',
    placeholder: 'Enter the name',
  },
  age: {
    name: 'age',
    type: 'number',
    id: 'age',
    label: 'Age',
    placeholder: 'Enter the age',
  },
  email: {
    name: 'email',
    type: 'text',
    id: 'email',
    label: 'Email',
    placeholder: 'Enter the email',
  },
  // gender: {
  //   name: 'gender',
  //   type: 'text',
  //   id: 'email',
  //   label: 'Email',
  // },
  password: {
    name: 'password',
    type: 'password',
    id: 'password',
    label: 'Password',
    placeholder: 'Create a password',
  },
  passwordRepeat: {
    name: 'passwordRepeat',
    type: 'password',
    id: 'passwordRepeat',
    label: 'Confirm Password',
    placeholder: 'Enter your password again',
  },
  img: {
    name: 'img',
    type: 'file',
    id: 'img',
    label: 'Upload image',
    placeholder: '',
  },
  t_c: {
    name: 't_c',
    type: 'checkbox',
    id: 't_c',
    label: 'Accept T&C',
    placeholder: '',
  },
  gender: {
    name: 'gender',
    id: 'gender',
    label: 'Gender',
    placeholder: 'Select the gender',
  },
  countries: {
    name: 'country',
    id: 'country',
    label: 'Country',
    placeholder: 'Select the country',
  },
};
